<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<!--
	Inspired by a vulnerable test case originally written for the OWASP Zed Attack Proxy (ZAP) project
	(http://www.owasp.org/index.php/OWASP_Zed_Attack_Proxy_Project) 
	Original Author: psiinon (psiinon@gmail.com).
-->
<%@ page import="java.util.*" %>
<head>
<title>Info Server Stack Trace (Originally part of ZAP-WAVE)</title>
</head>
<body>
<H2>Stack Trace (Originally part of ZAP-WAVE)</H2>
<H3>Description</H3>
This page will show a stack trace generated by the application.
<H3>Example</H3>
<%
out.println("<pre>");
Exception e = new Exception();
e.printStackTrace(new java.io.PrintWriter(out));
out.println("</pre>");
%>

</body>

